project:
  type: website
  output-dir: docs

website:
  title: "Boyko"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - biography.qmd
      - research.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

