---
title: ""
---

# Home

------------------------------------------------------------------------

### Boyko Terminal

The Boyko Terminal is a powerful quantitative financial analytics and risk desktop application designed to bridge the gap between low-cost platforms (e.g., TradingView) and legacy terminals (e.g., Bloomberg). It provides access to a wide array of global financial data and advanced quantitative tools, empowering users to make informed financial decisions.

#### [Learn More](https://boykowealth.com/)

### Top Public Projects

Boyko Wealth provides a variety of publicly available projects on GitHub. Some of the most popular are:

-   OpenFIGI Database Builder

-   Equity Options Chain Database

-   QuickFS API Financial Statement Builder

-   Supply Chain Database Webscraper

-   Bid-Ask Estimator - \[Modified Farshid Abdi and Angelo Ranaldo (2017)\]

-   SnowFlake Python Databse Tool With Okta Verification

### Top Private Projects

-   Boyko Terminal - Desktop Application

-   International Financial Database Infrastructure

-   International Investment Mapping Tool (Identifier Codes Across Regulators and Exchanges)

-   Bootstrapped Options Implied Volatility Curve & Implied Pricing Curve

-   Solana Automated Market Making Algorithm & Display
