---
title: ""
---

# Research

Brayden Boyko has completed a variety of Academic and Private research in his life. In collaboration with others, he has covered a wide range of topics related to finance, economics, and commodities. Additionally, Brayden created a rules-based automated asset valuation software; which provides practical information regarding North American, European, and Australian securities.

### Top Academic Research

-   [Forecasting Spreads In The Canadian Western Spring Wheat Market For Insurance Firms - Brayden Boyko & Brandon Choi. December 7, 2024.](https://boykowealth.com/wp-content/uploads/2024/12/forecasting_cwrs13_5.html)

-   [NYSE:NOG - Hedging The Future of Exploration and Production - Brayden Boyko. December 8, 2023.](https://boykowealth.com/wp-content/uploads/2025/01/NYSE_NOG-Hedging-The-Future-of-Exploration-and-Production-Brayden-Boyko.pdf)

-   [Pfizer: A Comparative Analysis of Hedging in the Global Pharmaceutical Industry - Brayden Boyko, Sofia Jimenez Lemish, Annabel Luchinger, Brooke Friesen. December 7, 2023.](https://boykowealth.com/wp-content/uploads/2025/01/Pfizer_-A-Comparative-Analysis-of-Hedging-in-the-Global-Pharmaceutical-Industryeport.pdf)

### Top Private Research

-   [Silicon Valley Bank (SVB) Insolvency Expectation - Brayden Boyko. November 2, 2022.](https://boykowealth.com/wp-content/uploads/2025/01/NASDAQ_SIVB-Brayden-Boyko.pdf)

-   [Equity Research: NYSE:PANL Pangaea Logistics Solutions (Portfolio Theory) - Brayden Boyko. April 3, 2023.](https://boykowealth.com/wp-content/uploads/2025/01/Equity-Research-NYSE_-PANL-Brayden-Boyko.pdf)

-   [Lumber To Gold As A Measure of Global Sensitivity To Volatility - Brayden Boyko. June 19, 2023.](https://boykowealth.com/wp-content/uploads/2025/01/Lumber-To-Gold-As-A-Measure-of-Global-Sensitivity-To-Volatility-Intermarket-Brayden-Boyko.pdf)

-   [Equity Research: NYSE:ZIM ZIM Integrated Shipping Services - Noah Shaffer & Brayden Boyko. July 11, 2023.](https://boykowealth.com/wp-content/uploads/2025/01/Equity-Research-NYSE_-ZIM-Noah-Shaffer.pdf)

-   [Equity Research: NASDAQ:CSIQ Canadian Solar Inc. - Luke Troutner & Brayden Boyko. August 30, 2024](https://boykowealth.com/wp-content/uploads/2025/01/Equity-Research-CSIQ-Luke-Troutner.pdf)

-   [Equity Research: NASDAQ:U Unity Software - Kevin Catulusi & Brayden Boyko. July 1, 2024.](https://boykowealth.com/wp-content/uploads/2025/01/NYSE_U-Unity-Software-Q22024-Kevin-Catulusi-Equity-Report.pdf)

### Automated Research Data Report Example

-   [NASDAQ:MSFT - Microsoft Corporation - Equity Data](https://www.linkedin.com/in/brayden-boyko/overlay/1723169005939/single-media-viewer/?profileId=ACoAADO7Bk8BnjgZjgMjthDQ3u7AxVBs9DjL-2s)
